import { ArkChatCompletions } from '@/chat-completions';

const apiKey = ''; // 火山引擎方舟的 api key
const model = ''; // 火山引擎方舟的接入点

const client = new ArkChatCompletions({
  apiKey,
});

const generator = client.stream({
  model,
  messages: [
    {
      role: 'user',
      content: '你好',
    },
  ],
});

for await (const chunk of generator) {
  console.log(JSON.stringify(chunk));
}

/**
{"choices":[{"delta":{"content":"","reasoning_content":"用户","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":1,"prompt_tokens":34,"total_tokens":35,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":1}}}
{"choices":[{"delta":{"content":"","reasoning_content":"现在","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":2,"prompt_tokens":34,"total_tokens":36,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":2}}}
{"choices":[{"delta":{"content":"","reasoning_content":"说","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":3,"prompt_tokens":34,"total_tokens":37,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":3}}}
{"choices":[{"delta":{"content":"","reasoning_content":"“","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":4,"prompt_tokens":34,"total_tokens":38,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":4}}}
{"choices":[{"delta":{"content":"","reasoning_content":"你","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":5,"prompt_tokens":34,"total_tokens":39,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":5}}}
{"choices":[{"delta":{"content":"","reasoning_content":"好","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":6,"prompt_tokens":34,"total_tokens":40,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":6}}}
{"choices":[{"delta":{"content":"","reasoning_content":"”","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":7,"prompt_tokens":34,"total_tokens":41,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":7}}}
{"choices":[{"delta":{"content":"","reasoning_content":"，","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":8,"prompt_tokens":34,"total_tokens":42,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":8}}}
{"choices":[{"delta":{"content":"","reasoning_content":"我","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":9,"prompt_tokens":34,"total_tokens":43,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":9}}}
{"choices":[{"delta":{"content":"","reasoning_content":"需要","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":10,"prompt_tokens":34,"total_tokens":44,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":10}}}
{"choices":[{"delta":{"content":"","reasoning_content":"友好","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":11,"prompt_tokens":34,"total_tokens":45,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":11}}}
{"choices":[{"delta":{"content":"","reasoning_content":"回应","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":12,"prompt_tokens":34,"total_tokens":46,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":12}}}
{"choices":[{"delta":{"content":"","reasoning_content":"。","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":13,"prompt_tokens":34,"total_tokens":47,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":13}}}
{"choices":[{"delta":{"content":"","reasoning_content":"首先","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":14,"prompt_tokens":34,"total_tokens":48,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":14}}}
{"choices":[{"delta":{"content":"","reasoning_content":"，","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":15,"prompt_tokens":34,"total_tokens":49,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":15}}}
{"choices":[{"delta":{"content":"","reasoning_content":"应该","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":16,"prompt_tokens":34,"total_tokens":50,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":16}}}
{"choices":[{"delta":{"content":"","reasoning_content":"回","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":17,"prompt_tokens":34,"total_tokens":51,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":17}}}
{"choices":[{"delta":{"content":"","reasoning_content":"一个","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":18,"prompt_tokens":34,"total_tokens":52,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":18}}}
{"choices":[{"delta":{"content":"","reasoning_content":"亲切","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":19,"prompt_tokens":34,"total_tokens":53,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":19}}}
{"choices":[{"delta":{"content":"","reasoning_content":"的","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":20,"prompt_tokens":34,"total_tokens":54,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":20}}}
{"choices":[{"delta":{"content":"","reasoning_content":"问候","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":21,"prompt_tokens":34,"total_tokens":55,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":21}}}
{"choices":[{"delta":{"content":"","reasoning_content":"，","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":22,"prompt_tokens":34,"total_tokens":56,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":22}}}
{"choices":[{"delta":{"content":"","reasoning_content":"比如","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":23,"prompt_tokens":34,"total_tokens":57,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":23}}}
{"choices":[{"delta":{"content":"","reasoning_content":"“","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":24,"prompt_tokens":34,"total_tokens":58,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":24}}}
{"choices":[{"delta":{"content":"","reasoning_content":"你","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":25,"prompt_tokens":34,"total_tokens":59,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":25}}}
{"choices":[{"delta":{"content":"","reasoning_content":"好","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":26,"prompt_tokens":34,"total_tokens":60,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":26}}}
{"choices":[{"delta":{"content":"","reasoning_content":"呀","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":27,"prompt_tokens":34,"total_tokens":61,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":27}}}
{"choices":[{"delta":{"content":"","reasoning_content":"，","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":28,"prompt_tokens":34,"total_tokens":62,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":28}}}
{"choices":[{"delta":{"content":"","reasoning_content":"很高兴","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":29,"prompt_tokens":34,"total_tokens":63,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":29}}}
{"choices":[{"delta":{"content":"","reasoning_content":"和","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":30,"prompt_tokens":34,"total_tokens":64,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":30}}}
{"choices":[{"delta":{"content":"","reasoning_content":"你","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":31,"prompt_tokens":34,"total_tokens":65,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":31}}}
{"choices":[{"delta":{"content":"","reasoning_content":"交流","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":32,"prompt_tokens":34,"total_tokens":66,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":32}}}
{"choices":[{"delta":{"content":"","reasoning_content":"，","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":33,"prompt_tokens":34,"total_tokens":67,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":33}}}
{"choices":[{"delta":{"content":"","reasoning_content":"有","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":34,"prompt_tokens":34,"total_tokens":68,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":34}}}
{"choices":[{"delta":{"content":"","reasoning_content":"什么","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":35,"prompt_tokens":34,"total_tokens":69,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":35}}}
{"choices":[{"delta":{"content":"","reasoning_content":"问题","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":36,"prompt_tokens":34,"total_tokens":70,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":36}}}
{"choices":[{"delta":{"content":"","reasoning_content":"或者","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":37,"prompt_tokens":34,"total_tokens":71,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":37}}}
{"choices":[{"delta":{"content":"","reasoning_content":"想","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":38,"prompt_tokens":34,"total_tokens":72,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":38}}}
{"choices":[{"delta":{"content":"","reasoning_content":"聊","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":39,"prompt_tokens":34,"total_tokens":73,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":39}}}
{"choices":[{"delta":{"content":"","reasoning_content":"的","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":40,"prompt_tokens":34,"total_tokens":74,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":40}}}
{"choices":[{"delta":{"content":"","reasoning_content":"都","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":41,"prompt_tokens":34,"total_tokens":75,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":41}}}
{"choices":[{"delta":{"content":"","reasoning_content":"可以","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":42,"prompt_tokens":34,"total_tokens":76,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":42}}}
{"choices":[{"delta":{"content":"","reasoning_content":"随时","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":43,"prompt_tokens":34,"total_tokens":77,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":43}}}
{"choices":[{"delta":{"content":"","reasoning_content":"说","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":44,"prompt_tokens":34,"total_tokens":78,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":44}}}
{"choices":[{"delta":{"content":"","reasoning_content":"~","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":45,"prompt_tokens":34,"total_tokens":79,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":45}}}
{"choices":[{"delta":{"content":"","reasoning_content":"”","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":46,"prompt_tokens":34,"total_tokens":80,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":46}}}
{"choices":[{"delta":{"content":"","reasoning_content":"这样","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":47,"prompt_tokens":34,"total_tokens":81,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":47}}}
{"choices":[{"delta":{"content":"","reasoning_content":"既","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":48,"prompt_tokens":34,"total_tokens":82,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":48}}}
{"choices":[{"delta":{"content":"","reasoning_content":"自然","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":49,"prompt_tokens":34,"total_tokens":83,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":49}}}
{"choices":[{"delta":{"content":"","reasoning_content":"又","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":50,"prompt_tokens":34,"total_tokens":84,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":50}}}
{"choices":[{"delta":{"content":"","reasoning_content":"符合","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":51,"prompt_tokens":34,"total_tokens":85,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":51}}}
{"choices":[{"delta":{"content":"","reasoning_content":"对话","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":52,"prompt_tokens":34,"total_tokens":86,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":52}}}
{"choices":[{"delta":{"content":"","reasoning_content":"的","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":53,"prompt_tokens":34,"total_tokens":87,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":53}}}
{"choices":[{"delta":{"content":"","reasoning_content":"氛围","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":54,"prompt_tokens":34,"total_tokens":88,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":54}}}
{"choices":[{"delta":{"content":"","reasoning_content":"。","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":55,"prompt_tokens":34,"total_tokens":89,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":55}}}
{"choices":[{"delta":{"content":"","reasoning_content":"现在","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":56,"prompt_tokens":34,"total_tokens":90,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":56}}}
{"choices":[{"delta":{"content":"","reasoning_content":"组织","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":57,"prompt_tokens":34,"total_tokens":91,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":57}}}
{"choices":[{"delta":{"content":"","reasoning_content":"语言","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":58,"prompt_tokens":34,"total_tokens":92,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":58}}}
{"choices":[{"delta":{"content":"","reasoning_content":"，","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":59,"prompt_tokens":34,"total_tokens":93,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":59}}}
{"choices":[{"delta":{"content":"","reasoning_content":"确保","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":60,"prompt_tokens":34,"total_tokens":94,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":60}}}
{"choices":[{"delta":{"content":"","reasoning_content":"简洁","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":61,"prompt_tokens":34,"total_tokens":95,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":61}}}
{"choices":[{"delta":{"content":"","reasoning_content":"友好","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":62,"prompt_tokens":34,"total_tokens":96,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":62}}}
{"choices":[{"delta":{"content":"","reasoning_content":"。","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":63,"prompt_tokens":34,"total_tokens":97,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":63}}}
{"choices":[{"delta":{"content":"你","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":65,"prompt_tokens":34,"total_tokens":99,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":64}}}
{"choices":[{"delta":{"content":"好","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":66,"prompt_tokens":34,"total_tokens":100,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":64}}}
{"choices":[{"delta":{"content":"呀","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":67,"prompt_tokens":34,"total_tokens":101,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":64}}}
{"choices":[{"delta":{"content":"，","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":68,"prompt_tokens":34,"total_tokens":102,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":64}}}
{"choices":[{"delta":{"content":"很高兴","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":69,"prompt_tokens":34,"total_tokens":103,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":64}}}
{"choices":[{"delta":{"content":"和","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":70,"prompt_tokens":34,"total_tokens":104,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":64}}}
{"choices":[{"delta":{"content":"你","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":71,"prompt_tokens":34,"total_tokens":105,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":64}}}
{"choices":[{"delta":{"content":"交流","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":72,"prompt_tokens":34,"total_tokens":106,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":64}}}
{"choices":[{"delta":{"content":"，","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":73,"prompt_tokens":34,"total_tokens":107,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":64}}}
{"choices":[{"delta":{"content":"有","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":74,"prompt_tokens":34,"total_tokens":108,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":64}}}
{"choices":[{"delta":{"content":"什么","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":75,"prompt_tokens":34,"total_tokens":109,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":64}}}
{"choices":[{"delta":{"content":"问题","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":76,"prompt_tokens":34,"total_tokens":110,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":64}}}
{"choices":[{"delta":{"content":"或者","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":77,"prompt_tokens":34,"total_tokens":111,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":64}}}
{"choices":[{"delta":{"content":"想","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":78,"prompt_tokens":34,"total_tokens":112,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":64}}}
{"choices":[{"delta":{"content":"聊","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":79,"prompt_tokens":34,"total_tokens":113,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":64}}}
{"choices":[{"delta":{"content":"的","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":80,"prompt_tokens":34,"total_tokens":114,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":64}}}
{"choices":[{"delta":{"content":"内容","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":81,"prompt_tokens":34,"total_tokens":115,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":64}}}
{"choices":[{"delta":{"content":"都","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":82,"prompt_tokens":34,"total_tokens":116,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":64}}}
{"choices":[{"delta":{"content":"可以","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":83,"prompt_tokens":34,"total_tokens":117,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":64}}}
{"choices":[{"delta":{"content":"随时","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":84,"prompt_tokens":34,"total_tokens":118,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":64}}}
{"choices":[{"delta":{"content":"说","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":85,"prompt_tokens":34,"total_tokens":119,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":64}}}
{"choices":[{"delta":{"content":"~","role":"assistant"},"index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":86,"prompt_tokens":34,"total_tokens":120,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":64}}}
{"choices":[{"delta":{"content":"","role":"assistant"},"finish_reason":"stop","index":0}],,"model":"doubao-seed-1-6-thinking-agent-preview","service_tier":"default","object":"chat.completion.chunk","usage":{"completion_tokens":86,"prompt_tokens":34,"total_tokens":120,"prompt_tokens_details":{"cached_tokens":0,"text_tokens":34},"completion_tokens_details":{"reasoning_tokens":64}}}
{"choices":[],,"model":"doubao-seed-1-6-thinking-agent-preview","object":"chat.completion.chunk","usage":{"completion_tokens":86,"prompt_tokens":34,"total_tokens":120,"prompt_tokens_details":{"cached_tokens":0},"completion_tokens_details":{"reasoning_tokens":64}}}
 */
